export const CONFIG = {
  NEXT_PUBLIC_LIFF_ID: process.env.NEXT_PUBLIC_LIFF_ID || "",
  NEXT_PUBLIC_LIFF_ID_INVOICE: process.env.NEXT_PUBLIC_LIFF_ID_INVOICE || "",
  NEXT_PUBLIC_LIFF_ID_TRACKING: process.env.NEXT_PUBLIC_LIFF_ID_TRACKING || "",
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  // NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL_LOCAL,
};
